---
abstract: "Unix::SearchPathGuess -- Make an educated guess for $ENV{'PATH'} in a Unixish system"
author:
    - "Miko O'Sullivan <miko@idocs.com>"
generated_by: home grown
license: perl
name: Unix-SearchPathGuess
provides:
    Unix::SearchPathGuess:
        file: lib/Unix/SearchPathGuess.pm
        version: 0.11
requires:
    File::Which: 1.09
    Test: 0
    perl: 5.003
version: 0.11
